@Path = /api/departments

### Get All
GET {{HostAddress}}{{Path}}
Accept: application/json

### Get by Id
GET {{HostAddress}}{{Path}}/aed80f25-4b0e-4e93-80dc-588f83d85ac5
Accept: application/json

### Get by Code
GET {{HostAddress}}{{Path}}/ti
Accept: application/json

### Post
POST {{HostAddress}}{{Path}}
Content-Type: application/json

{
  "code": "TST",
  "name": "Teste"
}

### Put
PUT {{HostAddress}}{{Path}}/aed80f25-4b0e-4e93-80dc-588f83d85ac5
Content-Type: application/json

{
  "id": "aed80f25-4b0e-4e93-80dc-588f83d85ac5",
  "code": "FIN",
  "name": "Financeiro Editado"
}

### Delete
DELETE {{HostAddress}}{{Path}}/aed80f25-4b0e-4e93-80dc-588f83d85ac5
Content-Type: application/json
