@HostAddress = http://localhost:5229
@Path = /api/user

### GetAll
GET {{HostAddress}}{{Path}}/
Accept: application/json

### Register
POST {{HostAddress}}{{Path}}/new-user
Content-Type: application/json

{
  "firstName": "Bruce",
  "lastName": "Wayne",
  "email": "bruce@waynecorp.com"
}