@HostAddress = http://localhost:5133
@Path = /api/identity
@AccessJwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NWE2YjUzMS05Y2ZhLTQ3OTEtYjc3MS04MWFkYjEyM2U1OTkiLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwianRpIjoiYjRhOGRiYTYtZGUzMy00MTcxLTk4ZjUtYjMzMTFkMTliMzZhIiwibmJmIjoxNzE0ODQ0NTM0LCJpYXQiOjE3MTQ4NDQ1MzQsImV4cCI6MTcxNDg1MTczNCwiaXNzIjoiSGVscERlc2siLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdCJ9.-j4qmGhlRJbKo7N4dNjL3GEeU9viWFz2TU1iLn_DaMs

### Register
POST {{HostAddress}}{{Path}}/new-account
Content-Type: application/json
Authorization: Bearer {{AccessJwt}}

{
  "firstName": "Diana",
  "lastName": "Themyscira",
  "departmentCode": "HR",
  "departmentName": "Human Resources",
  "email": "user2@email.com",
  "password": "Teste@123",
  "confirmPassword": "Teste@123"
}

### Authenticate
POST {{HostAddress}}{{Path}}/authenticate
Content-Type: application/json

{
  "email": "bruce@waynecorp.com",
  "password": "Teste@123"
}